### ISSUE TITLE
[Bug]: 'getLogicalBoundingClientRect' is not exported 

### ISSUE THREAD

**Issue by raurir** [cloudscape-design/component-toolkit#66]
### Package version

^1.0.0-beta

### Description

Using:
`"@cloudscape-design/board-components": "3.0.62"` & `"@cloudscape-design/components": "3.0.656"`

I get this error at build time: 
```
Attempted import error: 'getLogicalBoundingClientRect' is not exported from '@cloudscape-design/component-toolkit/internal' (imported as 'getLogicalBoundingClientRect').
```
We are using pdk, so the error is deep inside the stack; our project uses `CloudscapeReactTsWebsiteProject` which internally uses `@cloudscape-design`. i think the error stems from this repo though... 

### Reproduction

Hard to publish a reproduction of this issue - possible if needed - but commit de70d4c looks like it could be responsible.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/component-toolkit/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/component-toolkit/issues) for duplicate problems

**Comment by gethinwebster** [comment]
This is exported here: https://github.com/cloudscape-design/component-toolkit/blob/main/src/internal/index.ts#L25

It sounds like you need to upgrade to the latest version of @cloudscape-design/component-toolkit (perhaps via `npm update`)

**Comment by raurir** [comment]
Hmm, looks like it is not this repository...

Last build that works:
`/@cloudscape-design/components@3.0.611(react-dom@18.2.0)(react@18.2.0)`
which uses: `@cloudscape-design/component-toolkit': 1.0.0-beta.41`

Failing build after running upgrade-deps gives us:
`/@cloudscape-design/components@3.0.663(react-dom@18.3.1)(react@18.3.1)`
which uses: `@cloudscape-design/component-toolkit': 1.0.0-beta.41`
